DATABASE_URL=jdbc:mysql://localhost:3306/microservices
DATABASE_USERNAME=root
DATABASE_PASSWORD=dhartmi2910
DATABASE_DRIVER_CLASS_NAME=com.mysql.cj.jdbc.Driver
HIBERNATE_DDL_AUTO=update
HIBERNATE_DIALECT=org.hibernate.dialect.MySQLDialect
